### PR TITLE
Changed OS build order

### PR DESCRIPTION
**Pull request by Treeways**
Changed to build Windows, then macOS, then Linux, from most to least commonly used (as far as I know).

This _should_ be the last CI pull request for right now.

### CODE REVIEW

**Comment by anirudhb** [comment]
This is useless since all builds are performed in parallel.

**Comment by Treeways** [comment]
I noticed that OSes were built in this order. When Ubuntu compiled other builds were canceled.

**Comment by anirudhb** [comment]
If one build fails the others will fail as well. This makes sense so we don't waste build time for a build that will fail anyways.

**Comment by Treeways** [comment]
Ok, that makes sense.

**Pull request closed without merging**
